import Head from 'next/head'
import { Box, useTheme } from '@mui/material'
import TextInput from 'src/components/text-field/TextInput'

export default function Home() {
  const theme = useTheme()
  return (
    <>
      <Head>
        <title>Shop-katana</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box sx={{ margin: 6, maxWidth: '300px' }}>
        <TextInput label={'Multiple line'} fullWidth></TextInput>
      </Box>
    </>
  )
}
